import type { ContentSection, FAQEntry } from "@/config/content";

type DevicePage = { sections: ContentSection[]; faq: FAQEntry[] };
const l = (label: string, href: string) => ({ label, href });

export const devicePages: Record<string, DevicePage> = {
  "/dispositivos/iptv-android-tv/": {
    sections: [
      { heading: "Android TV: começa pela Google Play Store", paragraphs: ["Num televisor ou box com Android TV certificado, a forma mais segura de começar é procurar uma aplicação de reprodução na Google Play Store do próprio equipamento. Confirma o programador, as avaliações recentes e a data da última atualização antes de instalar.", "Android TV foi desenhado para comando remoto e ecrã grande. Evita escolher uma app móvel apenas porque tem o mesmo nome: a navegação pode ser difícil e algumas funções podem não responder ao comando."], links: [l("Comparar aplicações", "/apps/")] },
      { heading: "Configuração e experiência no sofá", paragraphs: ["Prepara o formato de acesso fornecido legitimamente e escreve os dados com atenção. Depois organiza favoritos, EPG e categorias para reduzir o tempo de procura. Se a aplicação permitir perfis, separa adultos e crianças.", "Para 4K, verifica descodificação HEVC, saída de vídeo e capacidade real da televisão. O selo 4K do dispositivo não garante que todas as fontes tenham essa qualidade."], links: [] },
      { heading: "Rede e diagnóstico", paragraphs: ["Usa Ethernet quando o equipamento tiver porta e estiver perto do router. Em Wi-Fi, prefere 5 GHz com sinal forte. Se houver interrupções, testa a mesma app no mesmo horário sem alterar várias opções ao mesmo tempo.", "Limpa cache apenas quando há sintomas concretos; limpar dados pode remover favoritos e credenciais."], links: [l("Problemas com a app", "/suporte/problemas-app/")] },
    ], faq: [{ question: "Android TV e Android são iguais?", answer: "Partilham tecnologia, mas Android TV tem interface e apps adaptadas ao comando e ao televisor." }, { question: "Posso instalar qualquer APK?", answer: "É tecnicamente possível em alguns equipamentos, mas aumenta o risco. Prefere a loja oficial e valida sempre a origem." }],
  },
  "/dispositivos/iptv-google-tv/": {
    sections: [
      { heading: "Google TV organiza conteúdo sobre Android TV", paragraphs: ["Google TV é uma experiência de interface construída sobre Android TV em dispositivos compatíveis. A configuração IPTV continua a depender da aplicação instalada e dos dados de acesso, não do ecrã inicial do Google TV.", "Procura a app na secção Aplicações, confirma compatibilidade com comando e evita confundir sugestões do Google TV com conteúdo fornecido pela aplicação."], links: [l("Android TV", "/dispositivos/iptv-android-tv/"), l("Apps IPTV", "/apps/")] },
      { heading: "Perfis, lista de observação e privacidade", paragraphs: ["Os perfis do Google TV ajudam a separar recomendações do sistema, mas não substituem perfis ou controlo parental dentro da app IPTV. Configura ambos quando existem crianças em casa.", "Revê permissões e dados associados à conta Google. Uma app de reprodução não precisa automaticamente de acesso a contactos ou localização precisa."], links: [] },
      { heading: "Chromecast integrado e rede", paragraphs: ["Muitos equipamentos Google TV também recebem transmissão por Google Cast. Usa essa opção apenas quando a app móvel e o conteúdo permitem cast; para utilização diária, uma app nativa costuma oferecer navegação mais consistente.", "Mantém telemóvel e Google TV na mesma rede e evita isolamento de dispositivos no router."], links: [l("Guia Chromecast", "/dispositivos/iptv-chromecast/"), l("Resolver buffering", "/suporte/buffering/")] },
    ], faq: [{ question: "Google TV precisa de telemóvel?", answer: "Não para apps nativas. O telemóvel é necessário apenas em fluxos de cast ou configuração específicos." }, { question: "Google TV é uma aplicação IPTV?", answer: "Não. É a interface do dispositivo; precisas de uma app compatível para reproduzir uma fonte IPTV legítima." }],
  },
  "/dispositivos/iptv-apple-tv/": {
    sections: [
      { heading: "Escolhe uma app criada para tvOS", paragraphs: ["No Apple TV, instala aplicações através da App Store do tvOS. Compara suporte a EPG, favoritos, legendas, áudio e formatos de acesso antes de pagar uma compra dentro da app.", "Uma aplicação para iPhone pode ter uma versão Apple TV diferente ou não estar disponível. Confirma sempre na televisão."], links: [l("Apps IPTV", "/apps/"), l("IPTV no iPhone e iPad", "/dispositivos/iptv-iphone-ipad/")] },
      { heading: "Comando, áudio e imagem", paragraphs: ["Testa a navegação com o Siri Remote, sobretudo troca de canal, retorno e abertura do guia. Ajusta correspondência de gama dinâmica e frame rate quando a televisão suporta essas opções; definições erradas podem causar ecrã preto momentâneo ao mudar de conteúdo.", "Para áudio, confirma a saída selecionada e testa sincronização antes de alterar a app."], links: [] },
      { heading: "Rede e ecossistema Apple", paragraphs: ["Apple TV 4K com Ethernet oferece uma ligação previsível; modelos apenas Wi-Fi dependem de boa cobertura. AirPlay pode ser útil para conteúdo autorizado, mas uma app nativa tende a ser mais prática para sessões longas.", "Não partilhes a password do Apple ID com quem só precisa de configurar a aplicação."], links: [] },
    ], faq: [{ question: "Posso usar uma app de iPhone no Apple TV?", answer: "Só se existir versão compatível com tvOS ou suporte AirPlay. Confirma na App Store do Apple TV." }, { question: "AirPlay substitui uma app nativa?", answer: "Pode transmitir conteúdo compatível, mas depende do telemóvel e da rede. Uma app nativa costuma ser mais autónoma." }],
  },
  "/dispositivos/iptv-roku/": {
    sections: [
      { heading: "Roku tem um ecossistema mais fechado", paragraphs: ["A disponibilidade de players IPTV no Roku varia por região e pelas regras da Roku Channel Store. Não assumes que uma aplicação disponível em Android ou Fire TV também existe no Roku.", "Antes de escolher o dispositivo para IPTV, pesquisa diretamente na loja do modelo e confirma que a aplicação aceita o formato de configuração que tens."], links: [l("Comparar dispositivos", "/dispositivos/")] },
      { heading: "Screen mirroring não é universal", paragraphs: ["Alguns telemóveis e computadores podem espelhar o ecrã para determinados modelos Roku, mas suporte, qualidade e controlo variam. iPhone usa AirPlay nos modelos compatíveis; Android depende do fabricante e do protocolo suportado.", "Espelhamento mantém o dispositivo emissor ocupado e pode aumentar latência. Testa antes de o considerar solução permanente."], links: [l("IPTV no telemóvel", "/dispositivos/iptv-telemovel/"), l("IPTV no Windows", "/dispositivos/iptv-windows/")] },
      { heading: "Quando escolher uma alternativa", paragraphs: ["Se a app necessária não estiver na loja, não procures canais privados ou instalações duvidosas. Um Chromecast com Google TV, Fire TV ou box Android TV certificada pode oferecer mais opções verificáveis.", "A melhor escolha é a que tem app mantida, atualizações e navegação adequada — não a que exige mais contornos."], links: [l("Chromecast", "/dispositivos/iptv-chromecast/"), l("Fire TV", "/dispositivos/iptv-firestick/")] },
    ], faq: [{ question: "Existe IPTV Smarters Pro no Roku?", answer: "A disponibilidade muda por região e política da loja. Confirma diretamente na Roku Channel Store do teu dispositivo." }, { question: "Posso instalar APK no Roku?", answer: "Não. Roku não usa APK Android e tem um ecossistema próprio." }],
  },
  "/dispositivos/iptv-chromecast/": {
    sections: [
      { heading: "Há dois tipos de experiência Chromecast", paragraphs: ["Um Chromecast clássico recebe conteúdo enviado por uma app no telemóvel; Chromecast com Google TV também executa apps nativas. Identifica o modelo antes de seguir instruções.", "No modelo clássico, procura o ícone Cast dentro de uma app compatível. Espelhar o ecrã inteiro é diferente e tende a consumir mais bateria."], links: [l("Google TV", "/dispositivos/iptv-google-tv/"), l("IPTV no telemóvel", "/dispositivos/iptv-telemovel/")] },
      { heading: "Telemóvel e TV precisam de se encontrar", paragraphs: ["Liga ambos à mesma rede Wi-Fi e confirma que o router permite comunicação entre dispositivos. Redes de convidados costumam isolar equipamentos e impedir que o botão Cast encontre a televisão.", "Depois de iniciar a transmissão, o Chromecast recebe o stream diretamente quando a app suporta cast verdadeiro; o telemóvel funciona como comando."], links: [] },
      { heading: "Resolver falhas de cast", paragraphs: ["Reinicia app e Chromecast, confirma atualizações e aproxima o dispositivo do router. Se o ícone aparece mas a reprodução não começa, testa outro conteúdo legítimo para separar problema de cast e problema da fonte.", "Evita alterar DNS, VPN e router ao mesmo tempo; cada mudança elimina pistas."], links: [l("IPTV não funciona", "/suporte/iptv-nao-funciona/")] },
    ], faq: [{ question: "Chromecast precisa de uma app na TV?", answer: "O modelo clássico não; recebe cast de uma app móvel compatível. Chromecast com Google TV pode instalar apps nativas." }, { question: "Porque não aparece o botão Cast?", answer: "A app pode não suportar cast, ou os dispositivos podem estar em redes diferentes ou isoladas." }],
  },
  "/dispositivos/iptv-nvidia-shield/": {
    sections: [
      { heading: "Android TV com foco em desempenho", paragraphs: ["NVIDIA Shield TV executa aplicações Android TV e oferece hardware forte para 4K, áudio e upscaling nos modelos compatíveis. Ainda assim, a qualidade final depende da fonte e da televisão.", "Instala a app pela Google Play Store e confirma compatibilidade com comando. Evita APKs antigos apenas porque aparecem num tutorial."], links: [l("Android TV", "/dispositivos/iptv-android-tv/")] },
      { heading: "Ajustes de imagem e áudio", paragraphs: ["Configura resolução, frequência, HDR e surround de acordo com o televisor e soundbar. Se houver cores lavadas ou áudio sem som, testa formatos automáticos antes de forçar uma opção avançada.", "O upscaling pode melhorar fontes abaixo de 4K, mas não cria detalhe ausente nem corrige compressão excessiva."], links: [l("Filmes e séries", "/canais/filmes-series/")] },
      { heading: "Ethernet, armazenamento e manutenção", paragraphs: ["Usa Gigabit Ethernet quando possível em streams de bitrate elevado. Mantém espaço livre, atualiza Shield Experience e reinicia depois de alterações importantes.", "Se uma app ficar lenta, limpa primeiro cache. Não apagues dados sem garantir que podes recuperar a configuração."], links: [l("Buffering", "/suporte/buffering/")] },
    ], faq: [{ question: "A NVIDIA Shield melhora todo o conteúdo para 4K?", answer: "Pode aplicar upscaling, mas não substitui uma fonte 4K nem corrige compressão fraca." }, { question: "TiviMate funciona na Shield?", answer: "TiviMate é disponibilizado para Android TV; confirma a versão e disponibilidade atual na Play Store." }],
  },
  "/dispositivos/iptv-windows/": {
    sections: [
      { heading: "Escolhe entre app dedicada e player", paragraphs: ["No Windows podes usar uma aplicação IPTV dedicada ou um player compatível com playlists. Uma app dedicada costuma organizar EPG e categorias; um player genérico é útil para testes simples.", "Descarrega software do site oficial ou Microsoft Store e mantém o Windows atualizado."], links: [l("M3U", "/guias/m3u/"), l("Xtream Codes", "/guias/xtream-codes/")] },
      { heading: "Ecrã, áudio e aceleração", paragraphs: ["Ativa aceleração por hardware quando o processador gráfico suporta o codec. Se surgirem blocos, ecrã verde ou uso elevado de CPU, compara com aceleração desligada.", "Ao ligar o PC à TV por HDMI, confirma o ecrã de saída, escala, resolução e dispositivo de áudio antes de culpar a aplicação."], links: [] },
      { heading: "Segurança e diagnóstico", paragraphs: ["Firewall pode pedir autorização na primeira execução; concede apenas o necessário em redes privadas. Não desatives proteção do sistema para instalar players desconhecidos.", "Para problemas, regista versão, codec e mensagem de erro. Testa a rede por cabo e compara com outro player legítimo para isolar a causa."], links: [l("Suporte", "/suporte/")] },
    ], faq: [{ question: "VLC serve para IPTV no Windows?", answer: "Pode abrir playlists compatíveis, mas oferece menos gestão de EPG e experiência de televisão do que apps dedicadas." }, { question: "Porque o vídeo usa muita CPU?", answer: "O codec pode não estar a ser descodificado por hardware. Revê aceleração e compatibilidade da placa gráfica." }],
  },
  "/dispositivos/iptv-android/": {
    sections: [
      { heading: "Escolhe uma app móvel confiável", paragraphs: ["No Android, usa a Google Play Store e verifica programador, permissões e atualizações. Uma app para telemóvel privilegia toque e orientação; para box ou TV escolhe a versão Android TV.", "Configura favoritos e bloqueio de ecrã para evitar toques acidentais durante reprodução."], links: [l("Apps IPTV", "/apps/")] },
      { heading: "Dados móveis e bateria", paragraphs: ["Vídeo consome dados de forma contínua. Define qualidade adequada, acompanha o consumo do Android e evita roaming inesperado. Em sessões longas, brilho e descodificação também aquecem o telemóvel.", "Usa Wi-Fi estável quando disponível e não tapes o dispositivo enquanto carrega e reproduz."], links: [] },
      { heading: "Transmitir para um ecrã maior", paragraphs: ["Se a app suporta Google Cast, envia o conteúdo para Chromecast ou Google TV na mesma rede. Adaptadores USB-C para HDMI dependem de suporte de vídeo do modelo.", "Desliga sessões em equipamentos partilhados e não mostres credenciais ao espelhar o ecrã."], links: [l("Chromecast", "/dispositivos/iptv-chromecast/"), l("Telemóvel", "/dispositivos/iptv-telemovel/")] },
    ], faq: [{ question: "Android móvel e Android TV usam a mesma app?", answer: "Nem sempre. Procura a versão otimizada para o tipo de ecrã e comando." }, { question: "Quanto consome IPTV em dados móveis?", answer: "Varia muito com qualidade e bitrate. Acompanha o consumo no sistema e usa limites do Android." }],
  },
  "/dispositivos/iptv-formuler/": {
    sections: [
      { heading: "Formuler combina box e interface MyTVOnline", paragraphs: ["As boxes Formuler são conhecidas pela aplicação MyTVOnline, cuja versão depende do modelo. Confirma se tens MYTVOnline2, MYTVOnline3 ou outra versão antes de seguir um tutorial.", "Atualiza o firmware através das definições oficiais e evita restaurar a box sem guardar as informações necessárias."], links: [l("M3U", "/guias/m3u/"), l("Xtream Codes", "/guias/xtream-codes/")] },
      { heading: "Adicionar uma fonte e organizar o EPG", paragraphs: ["Usa apenas dados fornecidos legitimamente e escolhe o tipo de portal ou playlist correspondente. Depois confirma fuso horário, EPG, grupos e favoritos.", "Se o guia estiver desalinhado, corrige hora e fonte do EPG antes de reinstalar a aplicação."], links: [l("Guia EPG", "/guias/epg/"), l("EPG não funciona", "/suporte/epg-nao-funciona/")] },
      { heading: "Comando, rede e manutenção", paragraphs: ["Personaliza botões apenas depois de testar navegação padrão. Ethernet tende a ser a escolha mais estável; em Wi-Fi, confirma banda e sinal no móvel da sala.", "Quando um canal falha, compara outros grupos e regista o padrão. Isso distingue um problema isolado de rede ou configuração."], links: [l("Canais não carregam", "/suporte/canais-nao-carregam/")] },
    ], faq: [{ question: "O que é MyTVOnline?", answer: "É a aplicação de televisão integrada em boxes Formuler. A versão e as funções variam conforme o modelo." }, { question: "Devo usar portal ou M3U?", answer: "Usa o formato suportado pela tua configuração e fornecido legitimamente. Não convertas dados sem necessidade." }],
  },
  "/dispositivos/iptv-telemovel/": {
    sections: [
      { heading: "O telemóvel é um ecrã e um comando", paragraphs: ["Android e iPhone podem reproduzir numa app móvel ou controlar Chromecast, AirPlay e dispositivos compatíveis. Decide se queres ver no próprio telefone ou enviar para a TV, porque o fluxo muda.", "Instala pela loja oficial e ativa bloqueio biométrico do dispositivo."], links: [l("Android", "/dispositivos/iptv-android/"), l("iPhone e iPad", "/dispositivos/iptv-iphone-ipad/")] },
      { heading: "Qualidade adaptada ao contexto", paragraphs: ["Num ecrã pequeno, resolução máxima nem sempre compensa bateria e dados. Escolhe qualidade equilibrada e usa auscultadores com atenção ao volume.", "Em Wi-Fi público, evita expor credenciais e termina sessões em equipamentos de terceiros."], links: [] },
      { heading: "Cast, AirPlay e cabos", paragraphs: ["Android pode usar Google Cast quando a app suporta; iPhone e iPad podem usar AirPlay com recetores compatíveis. Adaptadores físicos dependem da porta e do modelo.", "Para problemas de descoberta, confirma que os equipamentos estão na mesma rede e que a rede de convidados não os isola."], links: [l("Chromecast", "/dispositivos/iptv-chromecast/"), l("Apple TV", "/dispositivos/iptv-apple-tv/")] },
    ], faq: [{ question: "Qual app IPTV é melhor no telemóvel?", answer: "A melhor é a que tem origem confiável, suporta o teu formato de acesso e oferece controlos adequados ao sistema." }, { question: "Posso enviar a imagem para a TV?", answer: "Sim, quando app, telemóvel e recetor suportam Cast, AirPlay ou saída de vídeo por cabo." }],
  },
};
